language: generic
env:
  - CLICOLOR=1
matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.2 # OS X 10.14
    - os: osx
      osx_image: xcode10.1 # OS X 10.13
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode9.4
script:
  - ./test/run.sh
